### PR TITLE
Add support for themed icon

### LINKED ISSUE #822: Add Android 13 SDK33 themed icon

### PR DESCRIPTION
**Pull request by ghost**
This PR adds support for the Android 13's themed icon by reusing the foreground, which is already monochrome. Should close #822 and #875

### CODE REVIEW

**Comment by K1rakishou** [comment]
Sorry for such a long delay. 
Unfortunately, I don't think it's going to be that easy as just using the foreground icon twice because it removes the build flavor names from the icon. 

studio64_OZssRtjhBV

**Comment by K1rakishou** [comment]
Actually I think `ic_launcher_release_foreground` can be used as the monochrome icon for all flavors.

**Review by K1rakishou — APPROVED** [review]
LGTM

**Comment by ghost** [comment]
Great! Looking forward to a release, it's the only app I'm missing on my homescreen to have the adaptive icon x)

**Comment by ghost** [comment]
@K1rakishou any news on a new release including this?

**Comment by K1rakishou** [comment]
Yeah, I will try to do it this week.

**Pull request merged**
