### PR TITLE
Update Kun8.kt

### PR DESCRIPTION
**Pull request by tusx**
Media domain changed from media.8kun.top to media.128ducks.com, this is a possible fix. I have not tested it because I'm not an app dev but know the basic and this should solve the issue if the media URL is only being referenced from this single file.

apologies in advance if this is not how to do it.

### CODE REVIEW

**Comment by tusx** [comment]
the issue in mention is #559

**Comment by K1rakishou** [comment]
Seems like you need to do something more than just simply updating the media endpoint. All the images, both on the site and in the app, are replaced with some kind of placeholder.

image

**Comment by tusx** [comment]
Seems like the there Media server is not functioning correctly i was able to get some of the images loaded and others were 301 to this 404 image. I guess we just have to wait for them to sort out the server issues

**Comment by K1rakishou** [comment]
It seems to work fine with the new images so I'm going to merge this PR.

**Pull request merged**
