### PR TITLE
Add soyjak.party site support

### PR DESCRIPTION
**Pull request by chuddiechud**

### CODE REVIEW

**Comment by K1rakishou** [comment]
Oh no why would you do this.

**Comment by K1rakishou** [comment]
I'm going to ask KurobaEx users' opinion on merging this PR and if they don't mind then I will merge it, if they do mind it then I will not.

**Comment by K1rakishou** [comment]
Sorry for the late reply. After some thinking I decided that I won't merge this PR because I don't want this app to be associated with soyjacks. Sorry.

**Comment by bqv** [comment]
missing an 
```kotlin
import com.github.k1rakishou.chan.core.site.sites.Soyjakparty
```
anyway

**Pull request closed without merging**
